name: BetterPvP
version: '${project.version}'
main: io.github.sstudiosdev.BetterPvP
api-version: '1.13'
author: srsstaff_tv, sstudios, 1vcb, pichema
website: https://sstudiosdev.github.io/
depend: [Vault]
